version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 
    steps:
      - checkout 
      - run: echo "hello world"
  deploy:
    steps:
      - run : echo "this is running"
workflows:
    version: 2
    justtesting:
        jobs:
          - build
          - deploy